FROM eclipse-temurin:21-jre

ARG JMETER_VERSION=5.6.3

RUN apt-get update && \
    apt-get install -y curl tar \
    && curl -L \
    https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz \
    -o /tmp/jmeter.tgz \
    && tar -xzf /tmp/jmeter.tgz -C /opt \
    && mv /opt/apache-jmeter-${JMETER_VERSION} /opt/jmeter \
    && rm /tmp/jmeter.tgz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV JMETER_HOME=/opt/jmeter
ENV PATH=$JMETER_HOME/bin:$PATH

ENTRYPOINT ["jmeter"]